# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created: Fri Jan 13 11:37:51 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1553, 878)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../PhD@Plymouth/Concept project/CONCEPT_project_general/logo_concept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(70, 0, 1461, 821))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pushButton = QtGui.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(10, 320, 101, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit = QtGui.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 61, 27))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 80, 61, 27))
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 110, 61, 27))
        self.lineEdit_3.setText(_fromUtf8(""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 140, 61, 27))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 67, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 91, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox = QtGui.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(110, 170, 85, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.tab_5)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 320, 171, 27))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 101, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(10, 230, 101, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 200, 85, 27))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(self.tab_5)
        self.comboBox_4.setGeometry(QtCore.QRect(110, 230, 85, 27))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.label_12 = lg_view_widget(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(350, 30, 531, 321))
        self.label_12.setFrameShape(QtGui.QFrame.Box)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(350, 30, 531, 321))
        self.label_13.setFrameShape(QtGui.QFrame.Box)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(330, 10, 961, 545))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBox = QtGui.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 108, 131, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(1300, 10, 31, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.textEdit = QtGui.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(1300, 30, 151, 521))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = selection_widget(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 961, 545))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 540, 1251, 231))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.horizontalSlider = QtGui.QSlider(self.tab_10)
        self.horizontalSlider.setGeometry(QtCore.QRect(150, 10, 111, 29))
        self.horizontalSlider.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 10, 131, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab_10)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(150, 40, 111, 29))
        self.horizontalSlider_2.setProperty(_fromUtf8("value"), 10)
        self.horizontalSlider_2.setSliderPosition(10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.checkBox_6 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 40, 141, 22))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_15 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_15.setGeometry(QtCore.QRect(30, 140, 97, 22))
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkBox_20 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_20.setGeometry(QtCore.QRect(30, 160, 101, 22))
        self.checkBox_20.setChecked(False)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.checkBox_14 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_14.setGeometry(QtCore.QRect(30, 120, 131, 22))
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkBox_13 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_13.setGeometry(QtCore.QRect(30, 100, 121, 22))
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.horizontalSlider_4 = QtGui.QSlider(self.tab_10)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(150, 70, 111, 29))
        self.horizontalSlider_4.setProperty(_fromUtf8("value"), 33)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.checkBox_11 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 70, 97, 22))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkBox_12 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 180, 97, 22))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_10 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_10.setGeometry(QtCore.QRect(450, 50, 97, 22))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_3.setGeometry(QtCore.QRect(320, 20, 151, 22))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_4.setGeometry(QtCore.QRect(320, 50, 131, 22))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_21 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_21.setGeometry(QtCore.QRect(320, 170, 97, 22))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.checkBox_5 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 80, 131, 22))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_8 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_8.setGeometry(QtCore.QRect(320, 110, 131, 22))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_9 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_9.setGeometry(QtCore.QRect(320, 140, 131, 22))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.horizontalSlider_5 = QtGui.QSlider(self.tab_10)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(150, 180, 111, 21))
        self.horizontalSlider_5.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.checkBox_17 = QtGui.QCheckBox(self.tab_10)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 530, 121, 22))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.frame = QtGui.QFrame(self.tab_10)
        self.frame.setGeometry(QtCore.QRect(570, 10, 661, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 81, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.textEdit_3 = QtGui.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(410, 10, 231, 141))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.checkBox_16 = QtGui.QCheckBox(self.frame)
        self.checkBox_16.setGeometry(QtCore.QRect(20, 50, 71, 22))
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(120, 10, 211, 141))
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(350, 10, 67, 61))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.horizontalSlider_6 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(950, 120, 111, 29))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.label_14 = QtGui.QLabel(self.tab_11)
        self.label_14.setGeometry(QtCore.QRect(950, 150, 31, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalSlider_9 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(860, 140, 51, 29))
        self.horizontalSlider_9.setProperty(_fromUtf8("value"), 0)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName(_fromUtf8("horizontalSlider_9"))
        self.checkBox_22 = QtGui.QCheckBox(self.tab_11)
        self.checkBox_22.setGeometry(QtCore.QRect(840, 120, 97, 22))
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.label_19 = QtGui.QLabel(self.tab_11)
        self.label_19.setGeometry(QtCore.QRect(690, 10, 51, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalSlider_7 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(690, 30, 91, 21))
        self.horizontalSlider_7.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        self.horizontalSlider_8 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(690, 50, 91, 24))
        self.horizontalSlider_8.setProperty(_fromUtf8("value"), 30)
        self.horizontalSlider_8.setSliderPosition(30)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.label_15 = QtGui.QLabel(self.tab_11)
        self.label_15.setGeometry(QtCore.QRect(660, 30, 30, 40))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.checkBox_70 = QtGui.QCheckBox(self.tab_11)
        self.checkBox_70.setGeometry(QtCore.QRect(490, 30, 161, 21))
        self.checkBox_70.setObjectName(_fromUtf8("checkBox_70"))
        self.checkBox_71 = QtGui.QCheckBox(self.tab_11)
        self.checkBox_71.setGeometry(QtCore.QRect(490, 80, 161, 21))
        self.checkBox_71.setObjectName(_fromUtf8("checkBox_71"))
        self.horizontalSlider_28 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_28.setGeometry(QtCore.QRect(690, 80, 91, 24))
        self.horizontalSlider_28.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_28.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_28.setObjectName(_fromUtf8("horizontalSlider_28"))
        self.horizontalSlider_29 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_29.setGeometry(QtCore.QRect(690, 100, 91, 24))
        self.horizontalSlider_29.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_29.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_29.setObjectName(_fromUtf8("horizontalSlider_29"))
        self.label_58 = QtGui.QLabel(self.tab_11)
        self.label_58.setGeometry(QtCore.QRect(660, 80, 30, 41))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_20 = QtGui.QLabel(self.tab_11)
        self.label_20.setGeometry(QtCore.QRect(990, 150, 31, 31))
        self.label_20.setFrameShape(QtGui.QFrame.Box)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.line_2 = QtGui.QFrame(self.tab_11)
        self.line_2.setGeometry(QtCore.QRect(840, 20, 271, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_22 = QtGui.QLabel(self.tab_11)
        self.label_22.setGeometry(QtCore.QRect(840, 10, 81, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_11)
        self.pushButton_5.setGeometry(QtCore.QRect(930, 100, 21, 16))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_11)
        self.pushButton_6.setGeometry(QtCore.QRect(960, 100, 21, 16))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_23 = QtGui.QLabel(self.tab_11)
        self.label_23.setGeometry(QtCore.QRect(930, 40, 51, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_11)
        self.pushButton_7.setGeometry(QtCore.QRect(930, 80, 21, 16))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_11)
        self.pushButton_9.setGeometry(QtCore.QRect(960, 80, 21, 16))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_11)
        self.pushButton_10.setGeometry(QtCore.QRect(930, 60, 21, 16))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_11)
        self.pushButton_11.setGeometry(QtCore.QRect(960, 60, 21, 16))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.label_24 = QtGui.QLabel(self.tab_11)
        self.label_24.setGeometry(QtCore.QRect(840, 40, 57, 15))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.pushButton_12 = QtGui.QPushButton(self.tab_11)
        self.pushButton_12.setGeometry(QtCore.QRect(840, 80, 21, 16))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_11)
        self.pushButton_13.setGeometry(QtCore.QRect(870, 60, 21, 16))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.tab_11)
        self.pushButton_14.setGeometry(QtCore.QRect(840, 100, 21, 16))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.tab_11)
        self.pushButton_15.setGeometry(QtCore.QRect(870, 100, 21, 16))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.tab_11)
        self.pushButton_16.setGeometry(QtCore.QRect(840, 60, 21, 16))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.tab_11)
        self.pushButton_17.setGeometry(QtCore.QRect(870, 80, 21, 16))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.label_25 = QtGui.QLabel(self.tab_11)
        self.label_25.setGeometry(QtCore.QRect(1020, 40, 51, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.pushButton_18 = QtGui.QPushButton(self.tab_11)
        self.pushButton_18.setGeometry(QtCore.QRect(1020, 80, 21, 16))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.tab_11)
        self.pushButton_19.setGeometry(QtCore.QRect(1050, 60, 21, 16))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(self.tab_11)
        self.pushButton_20.setGeometry(QtCore.QRect(1020, 100, 21, 16))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.tab_11)
        self.pushButton_21.setGeometry(QtCore.QRect(1050, 100, 21, 16))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.tab_11)
        self.pushButton_22.setGeometry(QtCore.QRect(1020, 60, 21, 16))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.tab_11)
        self.pushButton_23.setGeometry(QtCore.QRect(1050, 80, 21, 16))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.label_31 = QtGui.QLabel(self.tab_11)
        self.label_31.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_11)
        self.label_32.setGeometry(QtCore.QRect(100, 100, 181, 16))
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_26 = QtGui.QLabel(self.tab_11)
        self.label_26.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalSlider_11 = QtGui.QSlider(self.tab_11)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(20, 30, 291, 24))
        self.horizontalSlider_11.setMaximum(3)
        self.horizontalSlider_11.setSingleStep(1)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_11.setTickInterval(1)
        self.horizontalSlider_11.setObjectName(_fromUtf8("horizontalSlider_11"))
        self.label_30 = QtGui.QLabel(self.tab_11)
        self.label_30.setGeometry(QtCore.QRect(280, 60, 61, 30))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_29 = QtGui.QLabel(self.tab_11)
        self.label_29.setGeometry(QtCore.QRect(180, 60, 61, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_27 = QtGui.QLabel(self.tab_11)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_11)
        self.label_28.setGeometry(QtCore.QRect(80, 60, 81, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(1270, 580, 180, 140))
        self.label_21.setFrameShape(QtGui.QFrame.Box)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 40, 61, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.checkBox_25 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_25.setGeometry(QtCore.QRect(40, 128, 121, 21))
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.checkBox_24 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_24.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.checkBox_24.setText(_fromUtf8(""))
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.pushButton_25 = QtGui.QPushButton(self.tab_2)
        self.pushButton_25.setGeometry(QtCore.QRect(180, 60, 61, 21))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.horizontalSlider_3 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(160, 170, 111, 21))
        self.horizontalSlider_3.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_3.setSliderPosition(50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.checkBox_19 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_19.setGeometry(QtCore.QRect(40, 190, 131, 20))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.checkBox_7 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 168, 141, 22))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_23 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_23.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(260, 10, 61, 21))
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.checkBox_26 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_26.setGeometry(QtCore.QRect(40, 210, 121, 21))
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.horizontalSlider_10 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(210, 100, 71, 24))
        self.horizontalSlider_10.setProperty(_fromUtf8("value"), 50)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName(_fromUtf8("horizontalSlider_10"))
        self.pushButton_24 = QtGui.QPushButton(self.tab_2)
        self.pushButton_24.setGeometry(QtCore.QRect(260, 60, 61, 21))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_26 = QtGui.QPushButton(self.tab_2)
        self.pushButton_26.setGeometry(QtCore.QRect(260, 40, 61, 21))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(30, 20, 611, 381))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 30, 51, 24))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.checkBox_18 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 60, 61, 31))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1553, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_COMVIZ = QtGui.QAction(MainWindow)
        self.actionAbout_COMVIZ.setObjectName(_fromUtf8("actionAbout_COMVIZ"))
        self.actionAbout_QT = QtGui.QAction(MainWindow)
        self.actionAbout_QT.setObjectName(_fromUtf8("actionAbout_QT"))
        self.actionControl_scene = QtGui.QAction(MainWindow)
        self.actionControl_scene.setObjectName(_fromUtf8("actionControl_scene"))
        self.actionOpen_Agent_knowledge_space = QtGui.QAction(MainWindow)
        self.actionOpen_Agent_knowledge_space.setObjectName(_fromUtf8("actionOpen_Agent_knowledge_space"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuAbout.addAction(self.actionAbout_COMVIZ)
        self.menuAbout.addAction(self.actionAbout_QT)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.comboBox_2.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionAbout_COMVIZ, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.about)
        QtCore.QObject.connect(self.actionAbout_QT, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.aboutQt)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.set_get_colour)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.language_game)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.load_agent)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.start_main_loop)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.modify_parameters)
        QtCore.QObject.connect(self.checkBox_25, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.modify_parameters)
        QtCore.QObject.connect(self.checkBox_70, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.modify_parameters)
        QtCore.QObject.connect(self.checkBox_71, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.modify_parameters)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.modify_parameters)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CONVIZ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "# agents", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "replicas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "training data", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "colour", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "shape", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "colour&shape", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "artificial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Language Game", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Guessing Game", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Discrimination Game", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Teaching type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Test type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("MainWindow", "LG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("MainWindow", "Direct", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("MainWindow", "LG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("MainWindow", "Direct", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Language Games", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Behaviours", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Start camera", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Detect faces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Edge Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "Circle Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("MainWindow", "PCA", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("MainWindow", "DFT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("MainWindow", "Average colour", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("MainWindow", "BoundingBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("MainWindow", "Adapt Thr.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("MainWindow", "Adapt Thr.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Get Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Get Contours", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setText(QtGui.QApplication.translate("MainWindow", "DFT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Get Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow", "SURF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("MainWindow", "STAR", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("MainWindow", "Show Saliency", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Load agent", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("MainWindow", "detect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Current\n"
"sensroy\n"
"input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "CV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setText(QtGui.QApplication.translate("MainWindow", "Colour Thr.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Tuning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "X_w\n"
"Y_w", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_70.setText(QtGui.QApplication.translate("MainWindow", "Gaze follows target", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_71.setText(QtGui.QApplication.translate("MainWindow", "Neck follows target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "X_w\n"
"Y_w", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Robot control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "-Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "-Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "-X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "gaze", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "-Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow", "-Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow", "-X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("MainWindow", "-Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MainWindow", "-Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MainWindow", "-X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Current state:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Robot behaviours", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "response\n"
"behaviour", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "run demo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "await", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "follow target", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), QtGui.QApplication.translate("MainWindow", "Robotville", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "rec hist", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_25.setText(QtGui.QApplication.translate("MainWindow", "histogram filter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("MainWindow", "clear hist", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("MainWindow", "show direction", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", "Detect movement", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setText(QtGui.QApplication.translate("MainWindow", "Set manual target", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setText(QtGui.QApplication.translate("MainWindow", "histogram filter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MainWindow", "load hist", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("MainWindow", "save hist", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Vision", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "CS view", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("MainWindow", "Dbg", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_COMVIZ.setText(QtGui.QApplication.translate("MainWindow", "About CONVIZ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_QT.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl_scene.setText(QtGui.QApplication.translate("MainWindow", "Control scene", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl_scene.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Agent_knowledge_space.setText(QtGui.QApplication.translate("MainWindow", "Open Agent knowledge space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from custom_widgets import selection_widget, lg_view_widget
